### ISSUE TITLE
in connectDB function, there doesn't need to be called inside of db.js

### ISSUE THREAD

**Issue by 20jasper** [100chats/100chats#15]
https://github.com/100chats/100chats/blob/main/server/models/db.js

On line 6, the connection function does not need to be ran

**Comment by nmpereira** [comment]
@20jasper please close this if resolved. Im assuming your #16 PR fixed the issue? If not, please provide more information.

**Comment by 20jasper** [comment]
Yep, I forgot to link that PR to this issue
